version: '3'
services:
  project1:
    build: ./docker/php
    volumes:
      - ./src/project1:/var/www/html
    ports:
      - 8888:80
    depends_on:
      - mysql
  project2:
    build: ./docker/php
    volumes:
      - ./src/project2:/var/www/html
    ports:
      - 8889:80
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 13306:3306
    volumes:
      - dbdata:/var/lib/mysql
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
volumes:
  dbdata: